### ISSUE TITLE
AbstractMethodError in TextBuildMessagesTranslator

### ISSUE THREAD

**Issue by unix-junkie** [JetBrains/process-output-parsers#2]
In TeamCity **10.0**, the contract of `jetbrains.buildServer.agent.messages.BuildMessagesTranslator` has changed (see [TW-45977](https://youtrack.jetbrains.com/issue/TW-45977)), so the plug-in doesn't work with versions newer than **9.1.x**, effectively making agents unusable:

```
[2017-04-13 15:05:32,672]   WARN -    jetbrains.buildServer.AGENT - Restarting agent due to a critical error. Problem logging a message java.lang.AbstractMethodError: jetbrains/buildServer/agent/messages/BuildMessagesTranslator.translateMessages(Ljetbrains/buildServer/agent/AgentRunningBuild;Ljava/util/List;)Ljava/util/List;
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.translate(BuildAgentImpl.java:508)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.translateAndSend(BuildAgentImpl.java:472)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.sendSingleMessage(BuildAgentImpl.java:441)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$1100(BuildAgentImpl.java:53)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl$AgentServerLoggerFacade.log(BuildAgentImpl.java:1201)
	at jetbrains.buildServer.agent.BaseServerLoggerFacade.startFlow(BaseServerLoggerFacade.java:205)
	at jetbrains.buildServer.agent.BaseServerLoggerFacade.logMessage(BaseServerLoggerFacade.java:197)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.LogAgentParametersStage.doBuildStage(LogAgentParametersStage.java:29)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:31)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor.doStages(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.BuildRunActionImpl.doStages(BuildRunActionImpl.java:75)
	at jetbrains.buildServer.agent.impl.BuildRunActionImpl.runBuild(BuildRunActionImpl.java:55)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:295)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:53)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:259)
	at java.lang.Thread.run(Thread.java:785)
```

Linked issue: [TW-49679](https://youtrack.jetbrains.com/issue/TW-49679).

**Comment by VladRassokhin** [comment]
Since plugin newer went into any production state, I'll just drop compatibility with 9.1
